### ISSUE TITLE
Crear una icona

### ISSUE THREAD

**Issue by EsteveAguilera** [InformaticsEmporda/InformaticsEmporda.github.io#1]
Necessitem una icona per fer branding i posar al grup de telegram, aquí al github, etc etc...

**Comment by utrescu** [comment]
Primer a proposta
![icon1](https://user-images.githubusercontent.com/2011002/36044370-afc49fa4-0dd2-11e8-936d-57932df42b2b.png)

**Comment by ctrl-alt-d** [comment]
En la meva etapa minimalista en la que em trobo, treuria el 'borde' negra de la pantalla i els botons de colors. 
En qualsevol cas, impressive!

**Comment by EsteveAguilera** [comment]
Ieps, el concepte m'agrada! 

Ja m'imagino que és una versiò molt alpha, però aquí van els meus 5 cèntims:

- No és quadrat, ni el cercle rodò 😅 
- Jo em quedaría amb el més plà possible, o sigui bicolor: blau i blanc. Per tant treuría el perfil negre, i els botonets del monitor en color blau
- Totes les línies de vent són rodonetes menys la de baix a l'esquerra

PS: potser sería millor seguir en una PR d'una branca que afegeixi una carpeta artworks o imatges o algo així... Les PRs van millor per comentar i veure progressos! 
Oh, i si hi pots posar els originals psd o el que sigui millor!

**Comment by EsteveAguilera** [comment]
Tanco la issue, el @utrescu ha creat un icona a la PR #2
